/**:
  ros__parameters:
    input_frame: "base_link"
    output_frame: "base_link"
    filter_field_name: "ring"
    filter_limit_min: 0
    filter_limit_max: 40
    filter_limit_negative: False
    keep_organized: False
