/**:
  ros__parameters:
    angular_velocity_offset_x: -0.00196
    angular_velocity_offset_y: -0.00370
    angular_velocity_offset_z: 0.009093101429651237
    angular_velocity_stddev_xx: 0.00820
    angular_velocity_stddev_yy: 0.00820
    angular_velocity_stddev_zz: 0.00820
