/**:
  ros__parameters:
    angular_velocity_offset_x: -0.00154
    angular_velocity_offset_y: -0.00387
    angular_velocity_offset_z: 0.008610502358459797
    angular_velocity_stddev_xx: 0.0082
    angular_velocity_stddev_yy: 0.0082
    angular_velocity_stddev_zz: 0.0082
