/**:
  ros__parameters:
    angular_velocity_offset_x: -0.00882
    angular_velocity_offset_y: -0.00660
    angular_velocity_offset_z: 0.00962
    angular_velocity_stddev_xx: 0.00258
    angular_velocity_stddev_yy: 0.00258
    angular_velocity_stddev_zz: 0.00258
